version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banco
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: app
    depends_on:
      - mysqldb
    build: ./Backend/banco
    restart: on-failure
    ports:
      - 5000:5000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/banco?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS=false
    ports:
      - 5000:5000
    volumes:
      - .m2:/banco/.m2
volumes:
  db:
 