version: "2.0"
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banco
    ports:
      - 3306:3306
  app:
    container_name: app
    depends_on:
      - mysqldb
    build: 
      context: ./Backend/banco
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/banco?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS=false
    ports:
      - 8080:8080